# Generated by Django 5.1.2 on 2024-10-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Catering', 'Catering'), ('Decoration', 'Decoration'), ('Photography', 'Photography'), ('Venues', 'Venues')], max_length=50),
        ),
    ]
