# Generated by Django 5.1.2 on 2024-10-27 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vendor'),
        ),
    ]
