# Generated by Django 5.1.2 on 2024-10-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_service_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='portfolio',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pricing',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
