# Generated by Django 5.1.2 on 2024-11-01 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_vendor_portfolio_alter_vendor_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.service'),
            preserve_default=False,
        ),
    ]
