# Generated by Django 5.1.2 on 2024-11-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_booking_service_remove_booking_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.vendor'),
            preserve_default=False,
        ),
    ]
